#!/bin/bash

actual_path=$(readlink -f "${BASH_SOURCE[0]}")
script_dir=$(dirname "$actual_path")

cd "$script_dir"

yad --html --uri=clock.htm --no-buttons --borders=0 --width=400 --height=400 --title="Time" --no-headers
